### ISSUE TITLE
Status of MultiKey

### ISSUE THREAD

**Issue by HelgeKrueger** [digitalbazaar/multikey-context#2]
I discovered this repository through the usage [here](https://codeberg.org/fediverse/fep/src/commit/94e2e371a15a037a7fd61494b98572ce0e46e5db/feps/fep-521a.md#example). See also the discussion [here](https://codeberg.org/fediverse/fep/pulls/105#issuecomment-933142).

The `@context` implies that a MultiKey object can only have the properties: "controller", "publicKeyMultibase", "secretKeyMultibase" and "revoked" (in addition to "@id" and "@type" which any json-ld object can have). I'm wondering about these choices:

- As far as I can see publishing a document with "secretKeyMultibase" should never happen. The only exception I can imagine is test data, and even then I'm not sure it's the best solution.
- If I want to use a MultiKey object in the context of verification, see .e.g. [here](https://w3c.github.io/vc-di-eddsa/#example-an-ed25519-public-key-encoded-as-a-multikey), I want to specify how long the key will stay valid, i.e. the property `expires`,  and not if the key has been `revoked`.

So my question is: How final is this document as a definition of `https://w3id.org/security#Multikey`?

**Comment by dmitrizagidulin** [comment]
Hi @HelgeKrueger! Thank you for raising these questions.

Re the MultiKey `expires` field - I think that's a great idea, and having checked with @msporny and other stakeholders, there seems to be no objections. So, the next steps would be to add it to this repo's context, and probably also add it to the various Data Integrity specs (like the [eddsa multikey examples](https://w3c.github.io/vc-di-eddsa/#example-an-ed25519-public-key-encoded-as-a-multikey) you linked to). Would you feel comfortable making the PRs?

**Comment by HelgeKrueger** [comment]
I can prepare a PR, but it might take me a week or two.

**Comment by dmitrizagidulin** [comment]
This issue can be closed once PR #3 is merged.
