### ISSUE TITLE
Release new major version w/ `expires`

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/multikey-context#4]
`expires` has been added to the context, this needs a major release.

**Comment by HelgeKrueger** [comment]
Any idea when this release will happen? Thanks.

**Comment by dlongley** [comment]
cc: @davidlehn, we need a major release here.

**Comment by dlongley** [comment]
Releasing this as a patch because the context was *incorrect* and did not match the live one; `expires` was not added to the context, but rather the URL is maps to was fixed to match the actual v1 context.

**Comment by dlongley** [comment]
Actually, just checked this more closely -- it was fixed up prior to a release, so this is a major change as `expires` was added since the last version. This is a major version release of this package, but the live context has stablized at v1.

**Comment by dlongley** [comment]
Version 2.0.0 has been released.
