### ISSUE TITLE
./dist/context.esm.js does not exist in build

### ISSUE THREAD

**Issue by rflechtner** [digitalbazaar/multikey-context#5]
The package.json of both v1 and v2 point consuming esm code to this file via `"module": "./dist/context.esm.js",` - however it does not exist in the packages published to npm (see https://www.npmjs.com/package/@digitalbazaar/multikey-context?activeTab=code).

**Comment by davidlehn** [comment]
That file was missing from the packed files.  Fixed in 2.0.1.
